### ISSUE TITLE
Dummy model won't run

### ISSUE THREAD

**Issue by SGeeversAtVortech** [Deltares/rtc-tools#1032]
In GitLab by @baayen on May 17, 2018, 11:36

A dummy model, consisting of a fixed input and its aliases, results in the following traceback:

```
2018-05-17 11:34:50,149 INFO Transcribing ensemble member 1/1
2018-05-17 11:34:50,150 ERROR .../casadi/core/slice.cpp:70: Assertion "stop<=len" failed:
Slice (start=0, stop=1, step=1) out of bounds with supplied length of 0
Traceback (most recent call last):
  File "example.py", line 35, in <module>
    run_optimization_problem(Example)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rtctools/util.py", line 88, in run_optimization_problem
    prob.optimize()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rtctools/optimization/optimization_problem.py", line 46, in optimize
    discrete, lbx, ubx, lbg, ubg, x0, nlp = self.transcribe()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rtctools/optimization/collocated_integrated_optimization_problem.py", line 749, in transcribe
    ensemble_member]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/casadi/casadi.py", line 11466, in __getitem__
    return self.get(False, s[0], s[1])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/casadi/casadi.py", line 11220, in get
    return _casadi.MX_get(self, *args)
RuntimeError: .../casadi/core/slice.cpp:70: Assertion "stop<=len" failed:
Slice (start=0, stop=1, step=1) out of bounds with supplied length of 0
```

The Modelica model is

```modelica
model Example
  input Modelica.SIunits.VolumeFlowRate Q_in(fixed = true);
  output Modelica.SIunits.VolumeFlowRate Q_release; 
  Deltares.ChannelFlow.SimpleRouting.BoundaryConditions.Inflow inflow1 annotation(
    Placement(visible = true, transformation(origin = {-90, 25}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Deltares.ChannelFlow.SimpleRouting.BoundaryConditions.Terminal terminal1 annotation(
    Placement(visible = true, transformation(origin = {45, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Deltares.ChannelFlow.SimpleRouting.Branches.Delay delay1 annotation(
    Placement(visible = true, transformation(origin = {-30, 20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(delay1.QOut, terminal1.QIn) annotation(
    Line(points = {{-20, 20}, {35, 20}, {35, 0}, {35, 0}}));
  connect(inflow1.QOut, delay1.QIn) annotation(
    Line(points = {{-80, 25}, {-45, 25}, {-45, 20}, {-40, 20}, {-40, 20}}));
  inflow1.Q = Q_in;
  Q_release = terminal1.Q;
  delay1.QOut.Q = delay1.QIn.Q; //delay(delay1.QIn.Q, 43200);
  annotation(Diagram(coordinateSystem(extent = {{-148.5, -105}, {148.5, 105}}, initialScale = 0.1, grid = {5, 5})));
end Example;
```

**Comment by SGeeversAtVortech** [comment]
In GitLab by @jvande42b on May 19, 2018, 02:36

Due to alias detection, this model has no states or alg_states. As a result, it hit an edge case in the RTC-Tools transcribe() logic.

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on May 26, 2018, 12:06

What should we even do in this case? There's nothing to optimize or simulate, so I would guess some sort of error makes sense.

**Comment by SGeeversAtVortech** [comment]
In GitLab by @jvande42b on Jul 9, 2018, 04:00

Why not let it run? As trivial as it is, it is technically still run-able.

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Sep 14, 2018, 16:37

Closing this as the exception no longer presents itself. 

This case is somewhat similar to the basic example, but with a delay branch instead of a storage. So no states/algebraic states from that indeed. It no longer fails, because delayed states now end up as algebraic states on the RTC-Tools side. Note that prescribing an initial state for  `Q_release` is not allowed anymore, as a value is already prescribed by the timeseries for Q_in. See model below that runs:

```Modelica
model Example
  input Modelica.SIunits.VolumeFlowRate Q_in(fixed = true);
  output Modelica.SIunits.VolumeFlowRate Q_release;
  Deltares.ChannelFlow.SimpleRouting.BoundaryConditions.Inflow inflow annotation(
    Placement(visible = true, transformation(origin = {-90, 25}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Deltares.ChannelFlow.SimpleRouting.BoundaryConditions.Terminal outfall annotation(
    Placement(visible = true, transformation(origin = {45, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Deltares.ChannelFlow.SimpleRouting.Branches.Delay branch_delay annotation(
    Placement(visible = true, transformation(origin = {-30, 20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(branch_delay.QOut, outfall.QIn) annotation(
    Line(points = {{-20, 20}, {35, 20}, {35, 0}, {35, 0}}));
  connect(inflow.QOut, branch_delay.QIn) annotation(
    Line(points = {{-80, 25}, {-45, 25}, {-45, 20}, {-40, 20}, {-40, 20}}));
  inflow.Q = Q_in;
  Q_release = outfall.Q;
  annotation(Diagram(coordinateSystem(extent = {{-148.5, -105}, {148.5, 105}}, initialScale = 0.1, grid = {5, 5})));
end Example;
```

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Sep 14, 2018, 16:37

closed
