### ISSUE TITLE
casadi not detected

### ISSUE THREAD

**Issue by SGeeversAtVortech** [Deltares/rtc-tools#1128]
In GitLab by @glubex on Nov 2, 2019, 21:46

Dear devs,

I'm using ArchLinux and have installed Casadi:
```
casadi /usr/lib/python3.7/site-packages/casadi/__init__.py
casadi /usr/lib/python3.7/site-packages/casadi/_casadi.so
casadi /usr/lib/python3.7/site-packages/casadi/casadi.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/
casadi /usr/lib/python3.7/site-packages/casadi/tools/__init__.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/bounds.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/graph/
casadi /usr/lib/python3.7/site-packages/casadi/tools/graph/__init__.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/graph/graph.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/in_out.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/structure.py
casadi /usr/lib/python3.7/site-packages/casadi/tools/structure3.py
```

But it is not detected by the download-examples script:
$ rtc-tools-download-examples
```
Traceback (most recent call last):
  File "/usr/bin/rtc-tools-download-examples", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'casadi>=3.5.0' distribution was not found and is required by rtc-tools
```

Why is it not working? Do I fave to fake pkg_resources?

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Nov 6, 2019, 16:09

My guess is that the version of CasADi you installed is too old. What is the output of `python -c "import casadi; print(casadi.__version__)"`?

EDIT:
I rarely if ever install anything in the system wide Python distribution, so I am not entirely sure what is wrong. It might also be related to pkg_resources / setuptools being out of date or not installed. If I just do it the virtualenv way, I works flawless:

```
python -m venv venv
. venv\bin\activate
pip install rtc-tools
rtc-tools-download-examples .
```

Either way I would expect to see any dependency on casadi>=3.5.0 pop up if you installed from PyPI. The current version of RTC-Tools is 2.3.2, which explicitly depends on pymoca==0.5.* and casadi==3.4.*. There is no dependency on casadi>=3.5.0, so I really wonder where that is coming from.

**Comment by SGeeversAtVortech** [comment]
In GitLab by @vreeken on Dec 6, 2019, 15:23

closed
